services:
  - type: web
    name: note-lock-pwa-static
    runtime: static
    autoDeployTrigger: commit
    buildCommand: echo "Using prebuilt static site"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
